### ISSUE TITLE
Python 2 and 3 interoperability

### ISSUE THREAD

**Issue by mcquin** [imagej/imagej-server#11]
[This line](https://github.com/imagej/imagej-server/blob/master/clients/python/imagej.py#L1) prevents Python 3 use:

```python
#! /usr/bin/env python2
```

Additionally, the Pythonic way of using `urllib.parse` in 2 and 3 environments is:

```python
from six.moves.urllib.parse import urlparse
```

From: [Cheat Sheet: Writing Python 2-3 compatible code](http://python-future.org/compatible_idioms.html#urllib-module)

**Comment by ctrueden** [comment]
Thanks @mcquin. Would you care to file a PR?

**Comment by mcquin** [comment]
Sure. I can do that.
